

sass:
  sass_dir: assets/css

plugins:
  - jekyll-autoprefixer
  - jekyll-seo-tag
  - jekyll-sitemap

title: "Follow the Father" # the name of your site, e.g. ACME Corp.
tagline: "An awesome tagline"
email: "your.email@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
author: Jeremy Green
url: "followthefather.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: G-RBDQHK9V5X
timezone: America/New_York
twitter:
  username: 
  card: summary #keep this to generate a twitter share card
